name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: latest
          # Where to store pnpm files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          run_install: true

      # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
      - name: Install dependencies
        run: pnpm i

      # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
      - name: Build Astro
        run: pnpm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: linusthe.deno.dev
          entrypoint: server/entry.mjs
          root: dist
